services:
  - type: web
    name: gguf-model-runner
    env: python
    plan: free
    buildCommand: pip install streamlit>=1.50.0 psutil>=5.9.0
    startCommand: streamlit run app.py --server.port=$PORT --server.address=0.0.0.0 --server.headless=true
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0